### ISSUE TITLE
Does stronghold work with macOS 10.12.6?

### ISSUE THREAD

**Issue by bknowles** [alichtman/stronghold#42]
I just installed it with pip, and it keeps bombing out:

```Enabling firewall...

Traceback (most recent call last):
  File "/usr/local/bin/stronghold", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/stronghold.py", line 356, in cli
    firewall_config()
  File "/usr/local/lib/python2.7/site-packages/stronghold.py", line 106, in firewall_config
    if sp.run("sudo -E -v", shell=True, stdout=sp.PIPE).returncode != 0:
AttributeError: 'module' object has no attribute 'run'
```

**Comment by alichtman** [comment]
Let me do some testing. It's working fine on my development environment, but that doesn't mean there's not a problem.

**Comment by alichtman** [comment]
Update: Found the issue, and have an eh fix (that happens to break other things in the pip install process.) Not pushing to master until I get those worked out, but my original problem diagnosis was correct. 

Fixes being made in `setup.py`.

**Comment by alichtman** [comment]
WIP on `pypi-setup-fixes` branch.

**Comment by alichtman** [comment]
@bknowles Could you test out the newest version I released?

Definitely reopen this if it doesn't work. It should force you to run it with Python3, and if you don't have that installed, you'll get a nice error message (not a stack trace.)

**Comment by bknowles** [comment]
Hmm.  I just tried installing it again with pip, and it didn't seem to force me to use pip3.

How do I tell what version is installed?  Does stronghold understand "--version" syntax?

**Comment by alichtman** [comment]
`-v` should give you the version

**Comment by bknowles** [comment]
I didn't see that in the help output from the version I had, which turned out to be 1.2.

I uninstalled that and re-installed with pip, which got me version 1.3.

Do I need to update pip somehow?

**Comment by bknowles** [comment]
Ahh.  `pip install --upgrade pip`, which also isn't mentioned anywhere on their --help output.

**Comment by bknowles** [comment]
And now I do finally have stronghold 1.4.  Let me do some more testing.

**Comment by alichtman** [comment]
Give me 2 minutes to roll out a new version with the `-v` fix.

**Comment by alichtman** [comment]
Fix is up.

**Comment by bknowles** [comment]
Okay, version 1.4 seemed to run to conclusion, without errors.  I think it was mostly just enabling stuff I had already set, but I wanted to be sure.

Thanks!

**Comment by alichtman** [comment]
No problem!

> I think it was mostly just enabling stuff I had already set, but I wanted to be sure.

Stronghold is designed to run safely on the same system as many times as you'd like. You can never damage a system by re-running it.

**Comment by bknowles** [comment]
Hmm.  Pip and pip3 are still finding version 1.4, without the -v change.

**Comment by bknowles** [comment]
Regardless, version 1.4 is now functional for me, so I'm not too worried about 1.4.1.

Thanks again!
